esphome:
  name: uponor-rf-thermostats
  friendly_name: Uponor RF Thermostats
  libraries:
  - "SPI"
  
external_components:
  - source:
      type: git
      url: https://github.com/ricardoschluter/uponor_knx_rf_thermostat
    components: ["knx_rf"]
    refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "nbBcNlrMOKkf+NNmZIvLcGWAjOFPezA83EGn/uh19f4="

ota:
  - platform: esphome
    password: "7a9b376b0a43119365a4bdbbd3deec35"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Uponor-Rf-Thermostats"
    password: "6hZQ2hIhyzHP"

captive_portal:

knx_rf:
  id: knx_gateway
    